// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfg3PkxaCGymkLQynCh07VHRp9FHbcI60',
    appId: '1:710751714437:web:74fbd69d1a705acc753dec',
    messagingSenderId: '710751714437',
    projectId: 'cloudcomputingproject-5deca',
    authDomain: 'cloudcomputingproject-5deca.firebaseapp.com',
    storageBucket: 'cloudcomputingproject-5deca.firebasestorage.app',
    measurementId: 'G-WY0SNGQ5QY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCz-lKC2EdR2Pu8kDzFlL9BMQEvIj1RZko',
    appId: '1:710751714437:android:e399cb75d4665346753dec',
    messagingSenderId: '710751714437',
    projectId: 'cloudcomputingproject-5deca',
    storageBucket: 'cloudcomputingproject-5deca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdIod9aballWA9D6HDdJDe27XdUGSfS6U',
    appId: '1:710751714437:ios:826ede1233e20e2f753dec',
    messagingSenderId: '710751714437',
    projectId: 'cloudcomputingproject-5deca',
    storageBucket: 'cloudcomputingproject-5deca.firebasestorage.app',
    iosBundleId: 'com.example.cloudcomputingproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdIod9aballWA9D6HDdJDe27XdUGSfS6U',
    appId: '1:710751714437:ios:826ede1233e20e2f753dec',
    messagingSenderId: '710751714437',
    projectId: 'cloudcomputingproject-5deca',
    storageBucket: 'cloudcomputingproject-5deca.firebasestorage.app',
    iosBundleId: 'com.example.cloudcomputingproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfg3PkxaCGymkLQynCh07VHRp9FHbcI60',
    appId: '1:710751714437:web:b8512c8ea44ba110753dec',
    messagingSenderId: '710751714437',
    projectId: 'cloudcomputingproject-5deca',
    authDomain: 'cloudcomputingproject-5deca.firebaseapp.com',
    storageBucket: 'cloudcomputingproject-5deca.firebasestorage.app',
    measurementId: 'G-0Z1QJXR8JJ',
  );
}
